# Generated by Django 3.0.1 on 2020-01-25 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('search', '0003_phobyusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='phobyusers',
            name='hobby',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='custom_hobby', to='accounts.Hobby'),
        ),
    ]
