# Generated by Django 3.0.1 on 2020-01-25 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_phobyusers_hobby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phobyusers',
            old_name='hobby',
            new_name='hobbyName',
        ),
    ]
