# Generated by Django 3.0.1 on 2020-02-10 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20200210_1837'),
        ('search', '0005_auto_20200125_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phobyusers',
            name='hobbyName',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='custom_hobby', to='posts.Hobby'),
        ),
    ]
