# Generated by Django 3.0.2 on 2020-02-10 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20200210_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phobyusers',
            name='email',
        ),
    ]
