# Generated by Django 3.0.1 on 2020-01-25 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hobby',
            old_name='hobby_name',
            new_name='hobbyName',
        ),
    ]
