# Generated by Django 3.0.1 on 2020-02-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200204_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
    ]
