# Generated by Django 3.0.2 on 2020-02-09 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200208_2050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
