# Generated by Django 3.0.1 on 2020-02-10 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20200210_1837'),
        ('accounts', '0007_delete_followers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hobby',
        ),
    ]
