# Generated by Django 3.0.1 on 2020-01-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=15)),
                ('user_password', models.CharField(max_length=15)),
                ('user_email', models.EmailField(max_length=100)),
                ('user_DOB', models.DateTimeField()),
                ('user_address', models.CharField(max_length=45)),
            ],
        ),
    ]
