# Generated by Django 3.0.2 on 2020-02-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_auto_20200209_0940'),
        ('userProfile', '0004_userprofile_friends'),
    ]

    operations = [
    ]
