# Generated by Django 3.0.1 on 2020-02-10 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0005_merge_20200209_2134'),
        ('userProfile', '0006_auto_20200209_1933'),
    ]

    operations = [
    ]
