# Generated by Django 3.0.1 on 2020-01-08 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedPost',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
