# Generated by Django 3.0.1 on 2020-01-09 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='createPosts',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_image', models.ImageField(blank=True, upload_to='posts_images/')),
                ('post_caption', models.TextField(max_length=140)),
                ('uploaded_on', models.DateTimeField(verbose_name=datetime.datetime(2020, 1, 9, 20, 17, 57, 211194))),
            ],
        ),
    ]
