# Generated by Django 3.0.1 on 2020-01-09 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createposts',
            name='uploaded_on',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 1, 9, 21, 37, 49, 250983)),
        ),
    ]
