# Generated by Django 3.0.1 on 2020-01-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200109_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createposts',
            name='post_image',
            field=models.ImageField(upload_to='posts_images/'),
        ),
        migrations.AlterField(
            model_name='createposts',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
