# Generated by Django 3.0.1 on 2020-01-24 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_createposts_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createposts',
            name='user',
        ),
    ]
