# Generated by Django 3.0.1 on 2020-01-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200109_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createposts',
            name='post_image',
        ),
    ]
