# Generated by Django 3.0.2 on 2020-02-09 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20200208_0714'),
        ('posts', '0005_auto_20200208_1322'),
    ]

    operations = [
    ]
