# Generated by Django 3.0.1 on 2020-02-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20200208_2050'),
        ('posts', '0010_createposts_comment'),
    ]

    operations = [
    ]
