# Generated by Django 3.0.1 on 2020-02-10 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_merge_20200209_2134'),
        ('posts', '0013_comments'),
    ]

    operations = [
    ]
